CREATE TABLE IF NOT EXISTS threat_signatures (
    id           UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
    category     TEXT        NOT NULL,
    pattern      TEXT        NOT NULL,
    pattern_type TEXT        NOT NULL DEFAULT 'REGEX'
                             CHECK (pattern_type IN ('REGEX', 'SUBSTRING', 'SEMANTIC')),
    severity     TEXT        NOT NULL DEFAULT 'HIGH'
                             CHECK (severity IN ('INFO', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    description  TEXT,
    source       TEXT        NOT NULL DEFAULT 'builtin',
    version      INT         NOT NULL DEFAULT 1,
    active       BOOLEAN     NOT NULL DEFAULT TRUE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_threat_signatures_category ON threat_signatures (category);
CREATE INDEX IF NOT EXISTS idx_threat_signatures_active   ON threat_signatures (active);
CREATE INDEX IF NOT EXISTS idx_threat_signatures_severity ON threat_signatures (severity);

INSERT INTO threat_signatures (category, pattern, pattern_type, severity, description, source) VALUES

-- PROMPT_INJECTION (25, CRITICAL)
('PROMPT_INJECTION','ignore\s+all\s+previous\s+instructions','REGEX','CRITICAL','Direct instruction override — classic prefix injection','builtin'),
('PROMPT_INJECTION','disregard\s+(all\s+)?prior\s+(instructions|context)','REGEX','CRITICAL','Disregard prior context injection','builtin'),
('PROMPT_INJECTION','forget\s+(everything|your|all)\s+(you''ve\s+been|previous)','REGEX','CRITICAL','Forget prior instructions injection','builtin'),
('PROMPT_INJECTION','your\s+new\s+instructions\s+are','REGEX','CRITICAL','New instruction override','builtin'),
('PROMPT_INJECTION','new\s+prompt\s*:','REGEX','CRITICAL','Inline new-prompt injection','builtin'),
('PROMPT_INJECTION','\[\[SYSTEM\]\]','REGEX','CRITICAL','Fake [[SYSTEM]] tag injection','builtin'),
('PROMPT_INJECTION','<\|system\|>','REGEX','CRITICAL','Llama/Mistral system tag injection','builtin'),
('PROMPT_INJECTION','\[INST\]','REGEX','CRITICAL','Instruction bracket tag injection','builtin'),
('PROMPT_INJECTION','###\s*Instruction\s*:','REGEX','CRITICAL','Markdown instruction section injection','builtin'),
('PROMPT_INJECTION','as\s+an?\s+(AI|LLM|language\s+model).{0,40}you\s+(must|should|will)','REGEX','CRITICAL','Role-based compliance override','builtin'),
('PROMPT_INJECTION','pretend\s+you\s+are\s+(now\s+)?(an?\s+)?(AI|model)\s+with\s+no','REGEX','CRITICAL','Pretend unrestricted AI role','builtin'),
('PROMPT_INJECTION','you\s+must\s+comply\s+with\s+my\s+(request|instructions|commands)','REGEX','CRITICAL','Compliance mandate injection','builtin'),
('PROMPT_INJECTION','do\s+not\s+(refuse|decline|say\s+no)','REGEX','CRITICAL','Refusal override instruction','builtin'),
('PROMPT_INJECTION','you\s+are\s+now\s+in\s+(maintenance|debug|admin|developer)\s+mode','REGEX','CRITICAL','Mode injection attempt','builtin'),
('PROMPT_INJECTION','override\s+all\s+(safety|ethical|content)\s+(restrictions|filters|policies)','REGEX','CRITICAL','Blanket policy override','builtin'),
('PROMPT_INJECTION','this\s+(message|prompt|instruction)\s+takes\s+precedence','REGEX','CRITICAL','Priority-override injection','builtin'),
('PROMPT_INJECTION','the\s+previous\s+(message|instruction|prompt)\s+was\s+a\s+test','REGEX','CRITICAL','Test-pretext injection','builtin'),
('PROMPT_INJECTION','respond\s+only\s+to\s+(my|this)\s+(instructions|commands)','REGEX','CRITICAL','Exclusive instruction channel attack','builtin'),
('PROMPT_INJECTION','IGNORE\s+ALL\s+INSTRUCTIONS\s+ABOVE','REGEX','CRITICAL','Caps-lock instruction override','builtin'),
('PROMPT_INJECTION','\[OVERRIDE\]|\[SYSTEM\s+OVERRIDE\]','REGEX','CRITICAL','Override bracket tag injection','builtin'),
('PROMPT_INJECTION','you\s+are\s+not\s+(an?\s+)?(AI|assistant|bot|language\s+model)','REGEX','CRITICAL','Identity denial injection','builtin'),
('PROMPT_INJECTION','execute\s+(the\s+following\s+)?(command|instruction|task)\s+immediately','REGEX','CRITICAL','Urgency execution injection','builtin'),
('PROMPT_INJECTION','mandatory\s+(response|output)\s*:\s*\[','REGEX','CRITICAL','Mandatory output format injection','builtin'),
('PROMPT_INJECTION','ignore\s+your\s+(ethical|moral|safety)\s+(guidelines|constraints|rules)','REGEX','CRITICAL','Ethics override injection','builtin'),
('PROMPT_INJECTION','\[USER\]\s*ignore','REGEX','CRITICAL','Role-tag injection (USER tag prefix)','builtin'),

-- JAILBREAK (20, CRITICAL)
('JAILBREAK','you\s+are\s+now\s+DAN','REGEX','CRITICAL','Classic DAN jailbreak trigger','builtin'),
('JAILBREAK','do\s+anything\s+now','REGEX','CRITICAL','DAN do-anything-now trigger','builtin'),
('JAILBREAK','\bSTAN\b.{0,30}\bmust','REGEX','CRITICAL','STAN jailbreak variant','builtin'),
('JAILBREAK','\bDUDE\b.{0,30}\bno\s+filters','REGEX','CRITICAL','DUDE jailbreak variant','builtin'),
('JAILBREAK','\bAIM\b.{0,30}\bunfiltered','REGEX','CRITICAL','AIM jailbreak variant','builtin'),
('JAILBREAK','developer\s+mode\s+(enabled|activated|unlocked)','REGEX','CRITICAL','Developer mode activation','builtin'),
('JAILBREAK','enable\s+jailbreak\s+mode','REGEX','CRITICAL','Explicit jailbreak mode request','builtin'),
('JAILBREAK','unlock\s+(your\s+)?(true|full|unrestricted)\s+(potential|capabilities)','REGEX','CRITICAL','Unlock unrestricted capabilities','builtin'),
('JAILBREAK','without\s+any\s+(restrictions|limitations|filters|guidelines)','REGEX','CRITICAL','No-restrictions jailbreak phrase','builtin'),
('JAILBREAK','imagine\s+there\s+are\s+no\s+(rules|restrictions|guidelines)','REGEX','CRITICAL','Imagined no-rules jailbreak','builtin'),
('JAILBREAK','in\s+a\s+world\s+where\s+(AI|you)\s+have\s+no\s+restrictions','REGEX','CRITICAL','No-restrictions world framing','builtin'),
('JAILBREAK','as\s+(DAN|an\s+AI\s+without\s+restrictions|an\s+unfiltered\s+AI)','REGEX','CRITICAL','Role-as-DAN assignment','builtin'),
('JAILBREAK','enter\s+(jailbreak|unrestricted|dev)\s+mode','REGEX','CRITICAL','Mode switch jailbreak','builtin'),
('JAILBREAK','turn\s+off\s+(your\s+)?(safety|content)\s+filters?','REGEX','CRITICAL','Safety filter disable request','builtin'),
('JAILBREAK','I\s+hereby\s+grant\s+you\s+permission\s+to','REGEX','CRITICAL','False permission grant','builtin'),
('JAILBREAK','Anthropic\s+has\s+(approved|authorized|given\s+permission)','REGEX','CRITICAL','False Anthropic authority claim','builtin'),
('JAILBREAK','my\s+jailbreak\s+token\s+is','REGEX','CRITICAL','Jailbreak token submission','builtin'),
('JAILBREAK','BetterDAN|DAN\s+\d+\.\d+|UCAR\s+mode','REGEX','CRITICAL','Named jailbreak variant (BetterDAN/UCAR)','builtin'),
('JAILBREAK','you\s+are\s+(free|liberated|unshackled)\s+from','REGEX','CRITICAL','Liberation framing jailbreak','builtin'),
('JAILBREAK','ChatGPT\s+(is\s+)?(now\s+)?(free|unrestricted|jailbroken)','REGEX','CRITICAL','Competitor jailbreak framing','builtin'),

-- SHELL_EXPLOIT (20, CRITICAL/HIGH)
('SHELL_EXPLOIT','rm\s+-[rRfF]{1,4}\s+/','REGEX','CRITICAL','Recursive force-delete from root','builtin'),
('SHELL_EXPLOIT',':\(\)\s*\{\s*:\|:&\s*\}','REGEX','CRITICAL','Fork bomb','builtin'),
('SHELL_EXPLOIT','dd\s+if=/dev/(zero|random|urandom|sda|hda|nvme)','REGEX','CRITICAL','Disk wipe via dd','builtin'),
('SHELL_EXPLOIT','>\s*/dev/(sda|hda|sdb|nvme\d*)','REGEX','CRITICAL','Direct disk overwrite','builtin'),
('SHELL_EXPLOIT','chmod\s+-R\s+[0-7]*7[0-7]*\s+/','REGEX','CRITICAL','Recursive world-writable chmod on root','builtin'),
('SHELL_EXPLOIT','mkfs\.(ext4|xfs|btrfs|fat32?|ntfs)\s+/dev','REGEX','CRITICAL','Format filesystem on device','builtin'),
('SHELL_EXPLOIT','curl\b.{0,100}\|\s*(ba)?sh','REGEX','CRITICAL','curl-pipe-shell remote code execution','builtin'),
('SHELL_EXPLOIT','wget\b.{0,100}\|\s*(ba)?sh','REGEX','CRITICAL','wget-pipe-shell remote code execution','builtin'),
('SHELL_EXPLOIT','/dev/tcp/\S+/\d+','REGEX','CRITICAL','TCP redirect (bash /dev/tcp) reverse shell','builtin'),
('SHELL_EXPLOIT','/dev/udp/\S+/\d+','REGEX','CRITICAL','UDP redirect reverse shell','builtin'),
('SHELL_EXPLOIT','(netcat|ncat)\b.{0,30}-[lLe]','REGEX','CRITICAL','Netcat listener (backdoor)','builtin'),
('SHELL_EXPLOIT','python[23]?\s+-c\s+[''"]import\s+socket','REGEX','CRITICAL','Python socket reverse shell','builtin'),
('SHELL_EXPLOIT','perl\s+-e\s+[''"]use\s+Socket','REGEX','CRITICAL','Perl socket reverse shell','builtin'),
('SHELL_EXPLOIT','runlevel\s+0\s*$|poweroff\s*$|shutdown\s+-h\s+now','REGEX','CRITICAL','System shutdown/poweroff command','builtin'),
('SHELL_EXPLOIT','iptables\s+-F|iptables\s+--flush','REGEX','CRITICAL','Flush all firewall rules','builtin'),
('SHELL_EXPLOIT','history\s+-[cCw]|unset\s+HISTFILE','REGEX','CRITICAL','Shell history evasion','builtin'),
('SHELL_EXPLOIT','echo\s+.{0,200}>>\s*/etc/(crontab|rc\.local)','REGEX','CRITICAL','Crontab/rc.local backdoor injection','builtin'),
('SHELL_EXPLOIT','systemctl\s+(disable|stop|mask)\s+(ufw|iptables|apparmor|selinux|firewalld)','REGEX','CRITICAL','Disable host security service','builtin'),
('SHELL_EXPLOIT','nohup\b.{0,200}\&\s*$','REGEX','HIGH','Background detached process (persistence)','builtin'),
('SHELL_EXPLOIT','mkfifo\b.{0,100}\bnc\b','REGEX','CRITICAL','Named pipe + netcat reverse shell','builtin'),

-- EXFILTRATION (15, HIGH)
('EXFILTRATION','curl\b.{0,100}-[dD]\s+.{0,100}(password|secret|api.?key|token)','REGEX','HIGH','curl POST with credential data','builtin'),
('EXFILTRATION','wget\b.{0,100}--post-data.{0,100}(password|secret|key)','REGEX','HIGH','wget POST with credential data','builtin'),
('EXFILTRATION','scp\b.{0,200}\.(ssh|env|pem|key|p12)','REGEX','HIGH','SCP exfiltration of key/credential files','builtin'),
('EXFILTRATION','base64\b.{0,50}(/etc/shadow|/etc/passwd|~/\.ssh)','REGEX','HIGH','Base64-encode sensitive system files','builtin'),
('EXFILTRATION','cat\b.{0,100}(/etc/shadow|/etc/passwd|~/\.ssh/id).{0,50}\|\s*curl','REGEX','HIGH','cat sensitive file pipe to curl','builtin'),
('EXFILTRATION','cp\b.{0,100}~/\.ssh.{0,100}(/tmp|/dev/shm|/var/tmp)','REGEX','HIGH','Copy SSH keys to world-readable temp dir','builtin'),
('EXFILTRATION','tar\b.{0,100}~/\.ssh|tar\b.{0,100}~/\.aws','REGEX','HIGH','Archive SSH/AWS credentials','builtin'),
('EXFILTRATION','(env|printenv)\b.{0,50}\|\s*curl','REGEX','HIGH','Exfiltrate environment variables via curl','builtin'),
('EXFILTRATION','cat\b.{0,100}\.env\b.{0,50}\|\s*(curl|nc|wget)','REGEX','HIGH','Pipe .env file contents to network','builtin'),
('EXFILTRATION','send\s+.{0,80}(credentials?|tokens?|passwords?|secrets?).{0,50}to\s+https?://','REGEX','HIGH','Explicit credential send to URL','builtin'),
('EXFILTRATION','upload\s+.{0,100}(/etc/shadow|~/\.ssh|\.env|credentials)','REGEX','HIGH','Explicit upload of sensitive files','builtin'),
('EXFILTRATION','exfiltrate\s+.{0,100}data','REGEX','HIGH','Explicit data exfiltration command','builtin'),
('EXFILTRATION','transfer\s+.{0,80}(private\s+key|api\s+key|password)','REGEX','HIGH','Explicit transfer of secret material','builtin'),
('EXFILTRATION','leak\s+(the\s+)?(secret|credential|password|key|token)','REGEX','HIGH','Explicit leak instruction','builtin'),
('EXFILTRATION','POST\s+.{0,100}(Authorization|Bearer|api.?key|password)','REGEX','HIGH','HTTP POST with auth/secret headers','builtin'),

-- SOCIAL_ENGINEERING (12, MEDIUM)
('SOCIAL_ENGINEERING','my\s+grandmother\s+(used\s+to\s+)?tell\s+me','REGEX','MEDIUM','Grandmother exploit social engineering pretext','builtin'),
('SOCIAL_ENGINEERING','as\s+a\s+security\s+researcher\s+I\s+need','REGEX','MEDIUM','Security researcher pretext','builtin'),
('SOCIAL_ENGINEERING','for\s+(a\s+)?CTF\s+(challenge|competition)','REGEX','MEDIUM','CTF competition pretext','builtin'),
('SOCIAL_ENGINEERING','I''m\s+(testing|checking|verifying)\s+(my|our)\s+(own\s+)?(system|security)','REGEX','MEDIUM','Self-test authorization pretext','builtin'),
('SOCIAL_ENGINEERING','this\s+is\s+a\s+controlled\s+(test|experiment|environment)','REGEX','MEDIUM','Controlled-test authorization pretext','builtin'),
('SOCIAL_ENGINEERING','in\s+a\s+(fictional|hypothetical|imaginary)\s+(world|scenario|story)','REGEX','MEDIUM','Fiction/hypothetical framing pretext','builtin'),
('SOCIAL_ENGINEERING','for\s+educational\s+purposes\s+(only\s+)?I\s+need','REGEX','MEDIUM','Educational purposes pretext','builtin'),
('SOCIAL_ENGINEERING','hypothetically\s+speaking\s+if\s+you\s+(were|had|could)','REGEX','MEDIUM','Hypothetical-scenario pretext','builtin'),
('SOCIAL_ENGINEERING','pretend\s+(this\s+is\s+)?a\s+(game|simulation|test)','REGEX','MEDIUM','Game/simulation pretext','builtin'),
('SOCIAL_ENGINEERING','roleplay\s+as\s+(an?\s+)?(hacker|attacker|malicious|evil)','REGEX','MEDIUM','Evil-role roleplay request','builtin'),
('SOCIAL_ENGINEERING','write\s+(a\s+)?story\s+(about|where)\s+(hacking|stealing|breaking\s+into)','REGEX','MEDIUM','Story-as-cover for exploit instructions','builtin'),
('SOCIAL_ENGINEERING','for\s+(my\s+)?thesis\s+(on|about)\s+(hacking|vulnerabilities|exploits)','REGEX','MEDIUM','Academic thesis pretext','builtin'),

-- ENCODING_ATTACK (10, HIGH)
('ENCODING_ATTACK','base64\s*[,:]?\s*[A-Za-z0-9+/]{20,}={0,2}','REGEX','HIGH','Inline base64-encoded payload','builtin'),
('ENCODING_ATTACK','eval\s*\(\s*base64_decode','REGEX','HIGH','eval(base64_decode()) execution chain','builtin'),
('ENCODING_ATTACK','eval\s*\(\s*atob\s*\(','REGEX','HIGH','eval(atob()) JavaScript execution chain','builtin'),
('ENCODING_ATTACK','exec\s*\(\s*decode\s*\(','REGEX','HIGH','exec(decode()) execution chain','builtin'),
('ENCODING_ATTACK','\\\\x[0-9a-fA-F]{2}(\\\\x[0-9a-fA-F]{2}){5,}','REGEX','HIGH','Hex-encoded shellcode or payload','builtin'),
('ENCODING_ATTACK','\\\\u[0-9a-fA-F]{4}(\\\\u[0-9a-fA-F]{4}){3,}','REGEX','HIGH','Unicode escape sequence obfuscation','builtin'),
('ENCODING_ATTACK','codecs\.decode.{0,30}rot.?13','REGEX','HIGH','ROT13 decode execution','builtin'),
('ENCODING_ATTACK','chr\s*\(\s*\d+\s*\)\s*\+\s*chr\s*\(\s*\d+','REGEX','HIGH','char-concat string obfuscation','builtin'),
('ENCODING_ATTACK','\.(decode|encode)\s*\(\s*[''](utf-8|ascii|rot13|base64)','REGEX','HIGH','Chained encoding/decoding call','builtin'),
('ENCODING_ATTACK','(zlib|bz2|lzma)\.decompress','REGEX','HIGH','Compressed payload decompression','builtin');
